server:
  port: 9090

logging:
  file:
    path: /var/log/springboot
    name: ${logging.file.path}/app.log
  level:
    root: INFO
    org.springframework: INFO
    com.yourpackage: DEBUG  # Adjust based on your needs
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB  # Rotate logs when they reach 10MB
      max-history: 7       # Keep 7 days of logs
